version: '3.3'

services:

  photoTrivia:
    image: makswinner/phototrivia:1.2-SNAPSHOT
    restart: always
    ports:
    - 8888:8888
    volumes:
    - /mnt/photos:/photos
    - ./application.properties:/application.properties
